apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: tigergraph

# source base yaml
bases:
- ../base

# revise blow to update global namespace 
namespace: default

# uncomment and revise blow to update images
# images:
# - name: tigergraph/tigergraph-k8s
#   newName: tigergraph001.azurecr.io/tigergraph
#   newTag: 3.2.0

configMapGenerator:
- name: env-config
  literals:
  - service.headless.name=tigergraph
  - pod.prefix=tigergraph
  - namespace=default
  - cluster_size=1
  - license=
  - ha=1
  - version=3.5.0
  - cluster_size.staging=0
  - version.staging=0

patchesStrategicMerge:
- patch-statfulset.yaml

