kind: ConfigMap 
apiVersion: v1 
metadata:
  name: tg-config
  namespace: default
  labels:
    app: tigergraph
data:
  init_tg_cfg: |
    System.HostList=[{"ID":"m1","Hostname":"127.0.0.1","Region":""}]
    System.SSH.User.Username=tigergraph
    System.SSH.User.Password=tigergraph
    System.SSH.User.Privatekey=/home/tigergraph/.ssh/tigergraph_rsa
    System.DataRoot=/home/tigergraph/tigergraph/data
    System.LogRoot=/home/tigergraph/tigergraph/log
    System.TempRoot=/tmp