apiVersion: batch/v1
kind: Job
metadata:
  name: installer
  namespace: default
  labels:
    app: tigergraph
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: tigergraph
    spec:
      serviceAccountName: tigergraph-installer
      initContainers:
      - name: init-tigergraph
        image: docker.tigergraph.com/tigergraph-k8s-installer:3.4.0
        env:
          - name: SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: service.headless.name
          - name: POD_PREFIX
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: pod.prefix
          - name: NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: namespace
          - name: CLUSTER_SIZE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: cluster_size
        command:
        - "/bin/sh"
        - "-c"
        - |
          # set -e;
          pod_cnt=0;
          echo -n Waiting for tigergraph;
          until [ ${pod_cnt} -eq ${CLUSTER_SIZE} ];
          do
            pod_cnt=0;
            for i in $(seq 1 ${CLUSTER_SIZE});
            do
              ready=$(kubectl get pod ${POD_PREFIX}-$((i-1)) -o json | jq -c '.status.containerStatuses[] | select(.name=="tigergraph").ready');
              if [ ${ready} == "true" ]; then pod_cnt=$((${pod_cnt}  + 1)); fi
            done;
            sleep 15;
            echo -n .;
          done;
          echo;

      containers:
      - name: cluster-installer
        image: docker.tigergraph.com/tigergraph-k8s-installer:3.4.0
        env:
        - name: LICENSE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: license
        - name: HA
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ha
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: service.headless.name
        - name: POD_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: pod.prefix
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: namespace
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -e;
          export SSHPASS='tigergraph';
          sshpass -e ssh -o StrictHostKeyChecking=no tigergraph@${POD_PREFIX}-0.${SERVICE_NAME}.${NAMESPACE} "
            if [[ ! -f /home/tigergraph/tigergraph/data/installation_flag ]] && [[ \$(ls -A /home/tigergraph/tigergraph/data/|grep -v lost|tail -1) ]]; then
              echo 'found lagacy data, skip installation'
            else
              touch /home/tigergraph/tigergraph/data/installation_flag;
              export PATH=/home/tigergraph/tigergraph/app/cmd:$PATH;
              cp /tmp/init_tg_cfg /tmp/tg_cfg;
              sed -i 's/\=/\: /g' /tmp/tg_cfg;
              echo >> /tmp/tg_cfg;
              jq -j '.System | \"System.AppRoot: \",.AppRoot' ~/.tg.cfg >> /tmp/tg_cfg;
              echo >> /tmp/tg_cfg;
              if [[ -z \"$LICENSE\" ]]; then
                jq -j '.System | \"System.License: \",.License' ~/.tg.cfg >> /tmp/tg_cfg;
              else
                echo \"System.License: ${LICENSE}\" >> /tmp/tg_cfg;
              fi;
              gadmin config init -i /tmp/tg_cfg --file /tmp/tg.cfg --ha ${HA};
              cp --remove-destination /tmp/tg.cfg ~/.tg.cfg;
              gadmin init cluster -y --skip-stop;
              rm /home/tigergraph/tigergraph/data/installation_flag;
            fi
          ";
      restartPolicy: OnFailure
  backoffLimit: 6
