apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tigergraph-installer
    namespace: default
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
