apiVersion: v1
kind: Service
metadata:
  labels:
    app: tigergraph
  name: tg-gui-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tigergraph
    guiserver: running
  ports:
  - port: 14240
    name: graphstudio
    targetPort: 14240
